% function [pathstr] = realignAalMaskSlowMethod(pathToAALToolbox)
% % The output of this function resides in the AAL mask folder of Analyze4D
% % wROI_MNI.nii 
% % and wwROI_MNI.nii
% 
% 
% filePaths = uipickfiles('Type' , {'*seg_sn.mat', 'Matlab (mat)'}, 'Prompt',...
%     'Please select ...seg_sn.mat file generated by the SPM unified segmentation', 'NumFiles', 1);
% [pathstr, name, ext] = fileparts(filePaths{1,1}); 
% 
% % First deformation- converts AAL from MNI space of AAL mask to MNI of the SPM T1 template
% matlabbatch{1}.spm.util.defs.comp{1}.sn2def.matname = {filePaths{1,1}};
% matlabbatch{1}.spm.util.defs.comp{1}.sn2def.vox = [NaN NaN NaN];
% matlabbatch{1}.spm.util.defs.comp{1}.sn2def.bb = [NaN NaN NaN
%                                                   NaN NaN NaN];
% matlabbatch{1}.spm.util.defs.ofname = '';
% matlabbatch{1}.spm.util.defs.fnames = {fullfile(pathToAALToolbox,'ROI_MNI_V4.nii,1')};
% matlabbatch{1}.spm.util.defs.savedir.savesrc = 1;
% matlabbatch{1}.spm.util.defs.interp = 0;
% 
% % Second Deformation- converts AAL mask from MNI space of SPM T1 to
% % subjects natiave space
% filePaths = uipickfiles('Type' , {'*seg_inv_sn.mat', 'Matlab (mat)'}, 'Prompt',...
%     'Please select ...seg_inv_sn.mat file generated by the SPM unified segmentation', 'NumFiles', 1);
% matlabbatch{2}.spm.util.defs.comp{1}.sn2def.matname = {filePaths{1,1}};
% matlabbatch{2}.spm.util.defs.comp{1}.sn2def.vox = [NaN NaN NaN];
% matlabbatch{2}.spm.util.defs.comp{1}.sn2def.bb = [NaN NaN NaN
%                                                   NaN NaN NaN];
%                                               
% filePaths = uipickfiles('Type' , {'*.nii', 'Nifti 3D (.nii)' ; '*.img', 'Analyze (.img + .hdr)'  }, 'Prompt',...
%     'Please specify a functional scan which will act as refreence for reslicing the AAL mask to native space', 'NumFiles', 1);
% 
% matlabbatch{2}.spm.util.defs.comp{2}.id.space = {filePaths{1,1}};
% matlabbatch{2}.spm.util.defs.ofname = '';
% matlabbatch{2}.spm.util.defs.fnames = {fullfile(pathToAALToolbox,'wROI_MNI_V4.nii,1')}; pause(0.5);
% matlabbatch{2}.spm.util.defs.savedir.savesrc = 1;
% matlabbatch{2}.spm.util.defs.interp = 0;
% dlg = ProgressDialog( ...
%     'StatusMessage', 'Preparing AAL mask....', ...
%     'Indeterminate', true);
% spm_jobman('run',matlabbatch);
% delete(dlg);
% 
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%5


% function [pathstr] = realignAalMaskSlowMethod(pathToAALToolbox)
% % The output of this function resides in the AAL mask folder of Analyze4D
% % wROI_MNI.nii 
% % and wwROI_MNI.nii
% 
% 
% filePaths = uipickfiles('Type' , {'*seg_sn.mat', 'Matlab (mat)'}, 'Prompt',...
%     'Please select ...seg_sn.mat file generated by the SPM unified segmentation', 'NumFiles', 1);
% [pathstr, name, ext] = fileparts(filePaths{1,1}); 
% 
% % First deformation- converts AAL from MNI space of AAL mask to MNI of the SPM T1 template
% matlabbatch{1}.spm.util.defs.comp{1}.sn2def.matname = {filePaths{1,1}};
% matlabbatch{1}.spm.util.defs.comp{1}.sn2def.vox = [NaN NaN NaN];
% matlabbatch{1}.spm.util.defs.comp{1}.sn2def.bb = [NaN NaN NaN
%                                                   NaN NaN NaN];
% matlabbatch{1}.spm.util.defs.ofname = '';
% matlabbatch{1}.spm.util.defs.fnames = {fullfile(pathToAALToolbox,'ROI_MNI_V4.nii,1')};
% matlabbatch{1}.spm.util.defs.savedir.savesrc = 1;
% matlabbatch{1}.spm.util.defs.interp = 0;
% 
% % Second Deformation- converts AAL mask from MNI space of SPM T1 to
% % subjects natiave space
% filePaths = uipickfiles('Type' , {'*seg_sn.mat', 'Matlab (mat)'}, 'Prompt',...
%     'Please select ...seg_inv_sn.mat file generated by the SPM unified segmentation', 'NumFiles', 1);
% matlabbatch{2}.spm.util.defs.comp{1}.inv.comp{1}.sn2def.matname = {filePaths{1,1}};
% matlabbatch{2}.spm.util.defs.comp{1}.inv.comp{1}.sn2def.vox = [NaN NaN NaN];
% matlabbatch{2}.spm.util.defs.comp{1}.inv.comp{1}.sn2def.bb = [NaN NaN NaN
%                                                   NaN NaN NaN];
%                                               
% filePaths = uipickfiles('Type' , {'*.nii', 'Nifti 3D (.nii)' ; '*.img', 'Analyze (.img + .hdr)'  }, 'Prompt',...
%     'Please specify a functional scan which will act as refreence for reslicing the AAL mask to native space', 'NumFiles', 1);
% 
% matlabbatch{2}.spm.util.defs.comp{1}.inv.space = {filePaths{1,1}};
% matlabbatch{2}.spm.util.defs.ofname = '';
% matlabbatch{2}.spm.util.defs.fnames = {fullfile(pathToAALToolbox,'wROI_MNI_V4.nii,1')}; pause(0.5);
% matlabbatch{2}.spm.util.defs.savedir.savesrc = 1;
% matlabbatch{2}.spm.util.defs.interp = 0;
% dlg = ProgressDialog( ...
%     'StatusMessage', 'Preparing AAL mask....', ...
%     'Indeterminate', true);
% spm_jobman('run',matlabbatch);
% delete(dlg);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [pathstr] = realignAalMaskSlowMethod(pathToAALToolbox)
% The output of this function resides in the AAL mask folder of Analyze4D
% wROI_MNI.nii 
% and wwROI_MNI.nii


% filePaths = uipickfiles('Type' , {'*seg_sn.mat', 'Matlab (mat)'}, 'Prompt',...
%     'Please select ...seg_sn.mat file generated by the SPM unified segmentation', 'NumFiles', 1);
% [pathstr, name, ext] = fileparts(filePaths{1,1}); 
% 
% % First deformation- converts AAL from MNI space of AAL mask to MNI of the SPM T1 template
% matlabbatch{1}.spm.util.defs.comp{1}.sn2def.matname = {filePaths{1,1}};
% matlabbatch{1}.spm.util.defs.comp{1}.sn2def.vox = [NaN NaN NaN];
% matlabbatch{1}.spm.util.defs.comp{1}.sn2def.bb = [NaN NaN NaN
%                                                   NaN NaN NaN];
% matlabbatch{1}.spm.util.defs.ofname = '';
% matlabbatch{1}.spm.util.defs.fnames = {fullfile(pathToAALToolbox,'ROI_MNI_V4.nii,1')};
% matlabbatch{1}.spm.util.defs.savedir.savesrc = 1;
% matlabbatch{1}.spm.util.defs.interp = 0;

% Second Deformation- converts AAL mask from MNI space of SPM T1 to
% subjects natiave space
filePaths = uipickfiles('Type' , {'*seg_inv_sn.mat', 'Matlab (mat)'}, 'Prompt',...
    'Please select ...seg_inv_sn.mat file generated by the SPM unified segmentation', 'NumFiles', 1);
[pathstr, name, ext] = fileparts(filePaths{1,1}); 
matlabbatch{1}.spm.util.defs.comp{1}.sn2def.matname = {filePaths{1,1}};
matlabbatch{1}.spm.util.defs.comp{1}.sn2def.vox = [NaN NaN NaN];
matlabbatch{1}.spm.util.defs.comp{1}.sn2def.bb = [NaN NaN NaN
                                                  NaN NaN NaN];
                                              
filePaths = uipickfiles('Type' , {'*.nii', 'Nifti 3D (.nii)' ; '*.img', 'Analyze (.img + .hdr)'  }, 'Prompt',...
    'Please specify a functional scan which will act as refreence for reslicing the AAL mask to native space', 'NumFiles', 1);

matlabbatch{1}.spm.util.defs.comp{2}.id.space = {filePaths{1,1}};
matlabbatch{1}.spm.util.defs.ofname = '';
matlabbatch{1}.spm.util.defs.fnames = {fullfile(pathToAALToolbox,'wROI_MNI_V4.nii,1')}; pause(0.5);
matlabbatch{1}.spm.util.defs.savedir.savesrc = 1;
matlabbatch{1}.spm.util.defs.interp = 0;
dlg = ProgressDialog( ...
    'StatusMessage', 'Preparing AAL mask....', ...
    'Indeterminate', true);
spm_jobman('run',matlabbatch);
delete(dlg);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%5