function [motionRegressors] = readSPMStyledMotionRegressors(numFilesToRead)
% reads the textfile generated by SPM after motion correction and return
% the columns Translation X,Y,Z and Yaw Pitch and roll

filePaths = uipickfiles('Type' , {'*.txt', 'Motion parameters File generated by SPM'}, 'Prompt', 'Please select the motion parameters file generated by SPM after motion correction', 'NumFiles', numFilesToRead);
filePaths = filePaths';
numFiles = size(filePaths,1);
% open file
fid = fopen(filePaths{1,1}, 'r');
[x, y, z, yaw, pitch, roll] = deal([]);

try
    while ~feof(fid)
        tline   = fgetl(fid);
        x       = [x; str2num(tline(01:16))];
        y       = [y; str2num(tline(17:32))];
        z       = [z; str2num(tline(33:48))];
        yaw     = [yaw; str2num(tline(49:64))];
        pitch   = [pitch; str2num(tline(65:80))];
        roll    = [roll; str2num(tline(81:96))];
    end
end
fclose(fid);
time                    = [1:numel(x)]';
motionRegressors.time   = time;
motionRegressors.x      = x;
motionRegressors.y      = y;
motionRegressors.z      = z;
motionRegressors.yaw    = yaw;
motionRegressors.pitch  = pitch;
motionRegressors.roll   = roll;
motionRegressors.allCombined = [time x y z yaw pitch roll];